pipeline {
    agent any
    
    parameters {
    string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
    string(name: 'ansible_tags', defaultValue: 'webserver', description: 'Tags for the Ansible playbook')    
    }

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage("Initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/William-eng/ansible-config-mgt'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
            }
        }

        stage('Test SSH Connections') {
            steps {
                script {
                    def hosts = [
                        //[group: 'tooling', ip: '172.31.24.134', user: 'ec2-user'],
                        //[group: 'tooling', ip: '172.31.29.63', user: 'ec2-user'],
                        //[group: 'nginx', ip: '172.31.21.241', user: 'ubuntu'],
                        //[group: 'db', ip: '172.31.18.140', user: 'ec2-user'],
			[group: 'artifactory', ip: '172.31.28.231', user: 'ubuntu']
                    ]
                    for (host in hosts) {
                        sshagent(['private-key']) {
                            sh "ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/key.pem ${host.user}@${host.ip} exit"
                        }
                    }
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                sshagent(['private-key']) {
                    ansiblePlaybook(
                        become: true,
                        credentialsId: 'private-key',
                        disableHostKeyChecking: true,
                        installation: 'ansible',
                        inventory: "${WORKSPACE}/${inventory}",
                        playbook: "${WORKSPACE}/playbooks/site.yml"
                    )
                }
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}

