---
- name: Install required packages
  apt:
    name:
      - openjdk-11-jdk
      - wget
    state: present
  become: yes

- name: Download Artifactory
  get_url:
    url: "https://releases.jfrog.io/artifactory/artifactory-pro/{{ artifactory_version }}/artifactory-pro-{{ artifactory_version }}-linux.tar.gz"
    dest: /tmp/artifactory.tar.gz
  become: yes

- name: Create Artifactory directory
  file:
    path: /opt/jfrog/artifactory
    state: directory
    owner: artifactory
    group: artifactory
    mode: '0755'
  become: yes

- name: Extract Artifactory
  unarchive:
    src: /tmp/artifactory.tar.gz
    dest: /opt/jfrog/artifactory
    remote_src: yes
  become: yes

- name: Create Artifactory user
  user:
    name: artifactory
    system: yes
    create_home: yes
  become: yes

- name: Create Artifactory service file
  copy:
    dest: /etc/systemd/system/artifactory.service
    content: |
      [Unit]
      Description=JFrog Artifactory
      After=network.target

      [Service]
      Type=simple
      User=artifactory
      ExecStart=/opt/jfrog/artifactory/artifactory-pro-{{ artifactory_version }}/bin/artifactory.sh start
      ExecStop=/opt/jfrog/artifactory/artifactory-pro-{{ artifactory_version }}/bin/artifactory.sh stop
      Restart=always

      [Install]
      WantedBy=multi-user.target
  become: yes

- name: Start and enable Artifactory service
  systemd:
    name: artifactory
    state: started
    enabled: yes
  become: yes

