---
# tasks file for installing Java and Artifactory on Ubuntu

- name: Install Java 11
  hosts: artifactory
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes


    - name: Configuring Java path
      ansible.builtin.shell: |
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> /etc/profile
        echo "PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile
      args:
        executable: /bin/bash

    - name: Reload profile to apply Java environment variables
      ansible.builtin.shell: source /etc/profile
      args:
        executable: /bin/bash

- name: Install JFrog Artifactory OSS
  hosts: artifactory
  become: yes
  tasks:
    - name: Add JFrog GPG key
      ansible.builtin.shell: |
        curl -fsSL https://releases.jfrog.io/artifactory/api/gpg/key/public | gpg --dearmor -o /usr/share/keyrings/jfrog-public.gpg

    - name: Add JFrog repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/jfrog-public.gpg] https://releases.jfrog.io/artifactory/artifactory-debs xenial main" | tee /etc/apt/sources.list.d/artifactory.list

    - name: Update apt cache after adding JFrog repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install JFrog Artifactory OSS
      ansible.builtin.apt:
        name: jfrog-artifactory-oss
        state: present

    - name: Start and enable Artifactory service
      ansible.builtin.systemd:
        name: artifactory
        state: started
        enabled: yes

    - name: Check status of Artifactory service
      ansible.builtin.command:
        cmd: systemctl status artifactory.service
      register: result

    - name: Print the status of Artifactory service
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
